name: devskim
"on":
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: 37 7 * * 3
permissions:
  actions: read
  contents: read
  security-events: write
jobs:
  devskim:
    name: devskim
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@85e6279cec87321a52edac9c87bce653a07cf6c2
      - name: analysis
        uses: microsoft/DevSkim-Action@4b5047945a44163b94642a1cecc0d93a3f428cc6
      - name: upload
        uses: github/codeql-action/upload-sarif@bc02a25f6449997c5e9d5a368879b28f56ae19a1
        with:
          sarif_file: devskim-results.sarif
